# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bm < Formula
  desc "A cross-platform CLI tool for efficient directory bookmarking and navigation"
  homepage "https://github.com/farhancdr/go-bookmark"
  version "1.0.1"

  on_macos do
    url "https://github.com/farhancdr/go-bookmark/releases/download/v1.0.1/go-bookmark_1.0.1_macOS_universal.tar.gz"
    sha256 "864472e84d15ec857afde5ac2d67a29e41f0f69be7e6eff7d5626d3c32d78b4e"

    def install
      bin.install "bm"
      bash_completion.install "completions/bm.bash" => "bm"
      zsh_completion.install "completions/bm.zsh" => "_bm"
      fish_completion.install "completions/bm.fish"
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/farhancdr/go-bookmark/releases/download/v1.0.1/go-bookmark_1.0.1_Linux_x86_64.tar.gz"
      sha256 "59320c4b14f4d21ef12f6efe7881477e77c322fad7c09ad0bac4966306078d0f"
      def install
        bin.install "bm"
        bash_completion.install "completions/bm.bash" => "bm"
        zsh_completion.install "completions/bm.zsh" => "_bm"
        fish_completion.install "completions/bm.fish"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/farhancdr/go-bookmark/releases/download/v1.0.1/go-bookmark_1.0.1_Linux_ARM64.tar.gz"
      sha256 "e1a672a3d8c5019df30820656cb0ef9be70f518f6db3857a7d89862d413d4a0d"
      def install
        bin.install "bm"
        bash_completion.install "completions/bm.bash" => "bm"
        zsh_completion.install "completions/bm.zsh" => "_bm"
        fish_completion.install "completions/bm.fish"
      end
    end
  end

  def caveats
    <<~EOS
      To enable directory navigation with `bm goto`, add the following to your shell configuration:

      For Bash/Zsh (~/.bashrc or ~/.zshrc):
        function bm_goto() {
            local target_dir=$(bm goto "$1")
            if [ -n "$target_dir" ] && [ -d "$target_dir" ]; then
                cd "$target_dir"
            else
                echo "Error: $target_dir"
            fi
        }
        alias bm_g='bm_goto'

      For Fish (~/.config/fish/config.fish):
        function bm_goto
            set target_dir (bm goto $argv[1])
            if test -n "$target_dir" -a -d "$target_dir"
                cd $target_dir
            else
                echo "Error: $target_dir"
            end
        end

      After adding, reload your shell with:
        source ~/.bashrc  # or ~/.zshrc or ~/.config/fish/config.fish

      Shell completions have been installed for bash, zsh, and fish.
    EOS
  end

  test do
    system "#{bin}/bm", "--version"
  end
end
